# Generated by Django 5.0.1 on 2024-02-01 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('parent_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=200)),
                ('item_description', models.TextField()),
                ('bo_code', models.CharField(max_length=45)),
                ('number_code', models.CharField(max_length=45)),
                ('x_code', models.CharField(max_length=45)),
                ('lpn_code', models.CharField(max_length=45)),
                ('log_number', models.CharField(max_length=45)),
                ('msrp_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_status_note', models.TextField()),
                ('quantity', models.IntegerField()),
                ('last_order_date', models.DateField(auto_now=True)),
                ('first_add_date', models.DateField(auto_now_add=True)),
                ('item_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemcategory')),
                ('item_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemstatus')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
    ]
