# Generated by Django 5.0.1 on 2024-02-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCategory',
            new_name='Item_Category',
        ),
        migrations.RenameModel(
            old_name='ItemStatus',
            new_name='Item_Status',
        ),
    ]
