# Generated by Django 5.0.1 on 2024-02-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_size_item_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
