# Generated by Django 5.0.1 on 2024-02-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_itemcategory_item_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Item',
        ),
    ]
