# Generated by Django 5.0.1 on 2024-02-01 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_bo_code_alter_item_item_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='first_add_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='last_order_date',
        ),
        migrations.AddField(
            model_name='item',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
