# Generated by Django 5.0.1 on 2024-02-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bid_start_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='layer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='msrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='shelf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('In stock', 'In stock'), ('Sold', 'Sold'), ('Returned', 'Returned')], default='In stock', max_length=20, null=True),
        ),
    ]
