# Generated by Django 5.0.1 on 2024-02-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_item_first_add_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_category_id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_status_id',
            new_name='status_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_status_note',
            new_name='status_note',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='item_category',
            old_name='category_name',
            new_name='name',
        ),
    ]
