# Generated by Django 5.0.1 on 2024-02-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_item_category_id_item_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='item_category',
            old_name='parent_category_id',
            new_name='parent_category',
        ),
    ]
