# Generated by Django 5.0.1 on 2024-02-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_bo_code_item_b_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='color',
            new_name='standard_color',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='size',
            new_name='standard_size',
        ),
        migrations.AddField(
            model_name='item',
            name='custom_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='custom_size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.item_category'),
            preserve_default=False,
        ),
    ]
