# Generated by Django 5.0.1 on 2024-02-08 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_custom_color_item_customize_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='added_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
