# Generated by Django 5.0.1 on 2024-02-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_item_case_number_alter_item_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='version',
            field=models.CharField(default='A', max_length=4),
        ),
    ]
