# Generated by Django 5.0.1 on 2024-02-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_item_ean_code_remove_item_fnsku_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='shelf',
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
