# Generated by Django 5.0.1 on 2024-03-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_remove_item_layer_remove_item_shelf_item_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="lpn_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="b_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="upc_ean_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
