# Generated by Django 5.0.1 on 2024-02-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_add_date_alter_item_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
