# Generated by Django 5.0.1 on 2024-02-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_bid_start_price_alter_item_layer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bo_code',
            new_name='b_code',
        ),
    ]
