# Generated by Django 5.0.1 on 2024-02-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_color_item_standard_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='custom_color',
            new_name='customize_color',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='custom_size',
            new_name='customize_size',
        ),
    ]
