# Generated by Django 5.0.1 on 2024-02-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_item_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ean_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fnsku_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lpn_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='upc_code',
        ),
        migrations.AddField(
            model_name='item',
            name='upc_ean_code',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
