# Generated by Django 5.0.1 on 2024-03-10 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_item_lpn_code_alter_item_b_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Purchase_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("b_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "upc_ean_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("lpn_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "msrp_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("add_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.supplier",
                    ),
                ),
            ],
        ),
    ]
