# Generated by Django 5.0.1 on 2024-03-11 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0020_alter_purchase_list_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase_list",
            name="supplier",
        ),
    ]
