# Generated by Django 5.0.1 on 2024-03-14 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0021_remove_purchase_list_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction_Product_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auction", models.IntegerField()),
                ("sequence", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("lot_number", models.IntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.item",
                    ),
                ),
            ],
        ),
    ]
