# Generated by Django 5.0.1 on 2024-02-08 20:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_profile_delete_staffprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff_Profile',
            new_name='Profile',
        ),
    ]
