# Generated by Django 5.0.1 on 2024-02-15 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_staff_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_modify_number_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
