# Generated by Django 5.0.1 on 2024-02-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_profile_last_modify_number_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='item_version',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
